version: '3.3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:main-ubuntu
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_DEFAULT_THEME: "dark"
    volumes:
      - gfdata:/var/lib/grafana:rw

  ttncollector:
    image: syn4pt1k/ttn_collector
    restart: always
    ports:
      - "1883:1883"

  iotrestaccess:
    image: syn4pt1k/iot_rest_access
    restart: always
    ports:
      - "8085:8085"

volumes:
  pgdata:
  gfdata:
